### PR TITLE
feat: List NFT collections from account details.

### PR DESCRIPTION
**Pull request by Sheng-Long**
**Description**:
Add Nft list and links to the token balances from account details

**Related issue(s)**:
https://github.com/hashgraph/hedera-mirror-node-explorer/issues/525

Fixes #

**Notes for reviewer**:
PR is built and depends on #692 , 692 should be merged first

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by Sheng-Long** [comment]
image

**Comment by Sheng-Long** [comment]
The above links directly to NftDetails

**Comment by Sheng-Long** [comment]
Notes from impromptu review:

Bug: On first load there is an issue with the tokens being displayed, it shows the same tokenID for every collection.  This is resolved on refresh

Feature: Collapsible collections on balance page, ellipsis if collection contains too many serial numbers

Feature: New separate page for individual collections owned by account, linked to from the balance page (show all serials owned by account in a certain collection)

**Review by svienot — APPROVED** [review]
Looks good.

**Review by ericleponner — APPROVED** [review]
Looks good to me.

**Pull request merged**
