### PR TITLE
feat: resolve accounts via kabuto name service (kns)

### PR DESCRIPTION
**Pull request by mehcode**
Signed-off-by: Ryan Leckey <ryan@launchbadge.com>

This PR allows looking up accounts by their domain registered on KNS via https://kabuto.sh.

### CODE REVIEW

**Comment by kenthejr** [comment]
@svienot @ericleponner would either of you mind reviewing this pull request?

**Comment by ericleponner** [comment]
@kenthejr it's on-going.
Did you run unit and e2e tests ?

**Comment by ericleponner** [comment]
@kenthejr  
Unit tests are failing with this error:

```
    SyntaxError: Cannot use import statement outside a module

      20 |
      21 | import {AccountInfo, AccountBalanceTransactions} from "@/schemas/HederaSchemas";
    > 22 | import {KNS, NameNotFoundError} from "@kabuto-sh/ns";
         | ^
      23 | import axios from "axios";
      24 |
      25 | let _nameService: KNS | null = null;

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/utils/NameService.ts:22:1)


```

It looks like there is an issue with @kabuto-sh/ns imports.
Can you investigate ?

**Comment by mehcode** [comment]
Fixed. The `@kabuto-sh/ns` library needed to add support for pre-esm Node 16 in order to get the unit tests to pass.

**Comment by ericleponner** [comment]
Thanks. Unit tests are ok now.
In the e2e tests, SearchBar.spec.ts is failing.
Could you investigate ?

**Comment by mehcode** [comment]
They aren't running at all for me. I'll try some more in a bit. It just spins forever.

```
~/Workspace/github.com/launchbadge/hedera-mirror-node-explorer lb-kabuto-ns 1m 11s
❯ npm run test:e2e

> hedera-explorer@0.1.0 test:e2e
> vue-cli-service test:e2e --url http://localhost:38920

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting e2e tests...
Still waiting to connect to Chrome, retrying in 1 second (attempt 18/62)
Still waiting to connect to Chrome, retrying in 1 second (attempt 19/62)
```

**Comment by mehcode** [comment]
E2E Tests Fixed. The changes to SearchUtil introduced a data race. Corrected.

**Comment by ericleponner** [comment]
@mehcode 

In SearchRequest.ts, line 251, we see:
`if (this.searchedId.includes(".")) {`

Shouldn't we test that `this.searchedId` ends with `".hh"` here ?
Right now, any value `0.0.nnnn` typed in search bar is passed to KNS.
I'm not sure it really makes sense.

**Comment by mehcode** [comment]
@ericleponner The Kabuto Name Service resolver works with quiet a few TLDs coming from Web23, Hashgraph.name, and Kabuto Name Service itself (`.blade`, `.cream`, `.hbar`, `.hh`, etc.).

What we could do is add a regex to ensure the last part is a-z instead of numerical. That'd stop talking to KNS for an account ID lookup. I can go ahead and add that.

**Comment by mehcode** [comment]
@ericleponner Adjusted. I ran both the unit and e2e tests locally and they still pass.

**Comment by mehcode** [comment]
@ericleponner Resolved conflicts and re-ran both unit and e2e tests.

**Comment by mehcode** [comment]
@ericleponner Rebased and resolved conflicts. This should be ready to merge.

**Review by ericleponner — APPROVED** [review]

**Pull request merged**
