### PR TITLE
Allow searching for an account by its Ethereum address

### PR DESCRIPTION
**Pull request by Neurone**
**Description**:
This PR modifies the search function in order to allow searching for an account by its Ethereum address.
This feature was already supported by the Mirror Node's API side.

Also, this PR move dependency from ethers.js to hethers.js for Ethereum related stuff.

**Related issue(s)**:

N/A

**Notes for reviewer**:

Searching by Ethereum address can return multiple results. We need to create an ad-hoc page to support showing a result with a list of multiple accounts.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by ericleponner** [comment]
According [Mirror Node API spec](http://testnet.mirrornode.hedera.com/api/v1/docs/#/accounts/getAccountByIdOrAliasOrEvmAddress), api/v1/accounts/{idOrAliasOrEvmAddress} returns an AccountBalanceTransactions entity.

Where does this AccountsBalanceTransactionsResponse entity come from ?

**Comment by Neurone** [comment]
I created `AccountsBalanceTransactionsResponse` as a structure to handle multiple results (multiple accounts can use the same ECDSA key, and so they can have the same evmAddress), but I can get rid of it if you prefer, waiting for an official implementation in the schema and Node's API.

**Comment by Neurone** [comment]
@ericleponner I removed the new schema, we will introduce that in the future. I also moved the dependency from ethers.js to hethers.js

**Comment by Neurone** [comment]
Hi @ericleponner, the PR has now conflicts with the main branch. If you plan to accept this, I can resolve those conflicts; otherwise I'll close this.

**Comment by ericleponner** [comment]
Hi Giuseppe,
Please hold your PR until friday. I need to refresh my brain before giving an answer.
Thanks.

**Comment by Neurone** [comment]
Implemented here: https://github.com/hashgraph/hedera-mirror-node-explorer/pull/272

**Pull request closed without merging**
