### PR TITLE
Show build release

### LINKED ISSUE #137: Display the build version, not just the build date/time
### Problem

When submitting tickets, it requests that I have the build version number but https://hashscan.io/ only displays the build date/time.

### Solution

Can we display the build version, next to the build date/time?

### Alternatives

None

### PR DESCRIPTION
**Pull request by Neurone**
**Description**:
This PR shows build release in the footer, as specified in [this comment](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/171#issuecomment-1553432264).

**Related issue(s)**:
Fixes #137 #585 

**Notes for reviewer**:
This PR replaces #171 

**Checklist**
- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by svienot** [comment]
Unit tests pass. It is the coverage report generation which fails at the end -- I assume because the PR comes from a fork.

**Comment by svienot** [comment]
Thank you @Neurone for your contribution!

**Review by svienot — APPROVED** [review]

**Comment by svienot** [comment]
@Neurone I approved your changes but I cannot merge the PR because your commit is not signed...

**Comment by Neurone** [comment]
Updated with signature.

About Sonar, I don't know why it returns an error, the only notable problem seems to be with the missing SONAR_TOKEN.

Here the log for my [PR](https://github.com/hashgraph/hedera-mirror-node-explorer/actions/runs/5022631216/jobs/9006323434?pr=604):

```
Run SonarSource/sonarcloud-github-action@v1.7
  with:
    projectBaseDir: .
  env:
    LC_ALL: C.UTF-8
    GITHUB_TOKEN: ***
    SONAR_TOKEN: 
/usr/local/bin/docker run --name e226942db9147b8c4e44bb4aeb7ba3420805_380f36 --label 60e226 --workdir /github/workspace --rm -e "LC_ALL" -e "GITHUB_TOKEN" -e "SONAR_TOKEN" -e "INPUT_ARGS" -e "INPUT_PROJECTBASEDIR" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_EVENT_PATH" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/hedera-mirror-node-explorer/hedera-mirror-node-explorer":"/github/workspace" 60e226:942db9147b8c4e44bb4aeb7ba3420805
Set the SONAR_TOKEN env variable.
```

And here the log for a working PR (i.e., [592](https://github.com/hashgraph/hedera-mirror-node-explorer/actions/runs/4957954261/jobs/8870240409)) :

```
Run SonarSource/sonarcloud-github-action@v1.7
  with:
    projectBaseDir: .
  env:
    LC_ALL: C.UTF-8
    GITHUB_TOKEN: ***
    SONAR_TOKEN: ***
/usr/local/bin/docker run --name e226d76a2c8e5bc644ce86e97c54a2a8f0fb_82fbbb --label 60e226 --workdir /github/workspace --rm -e "LC_ALL" -e "GITHUB_TOKEN" -e "SONAR_TOKEN" -e "INPUT_ARGS" -e "INPUT_PROJECTBASEDIR" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_EVENT_PATH" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/hedera-mirror-node-explorer/hedera-mirror-node-explorer":"/github/workspace" 60e226:d76a2c8e5bc644ce86e97c54a2a8f0fb
```

**Comment by Neurone** [comment]
@svienot  It seems the process goes out of memory for some reason between different tests. Probably it is not correctly freeing memory in the previous steps. I was able to force freeing the old heap (so it remains always under the specified value) using the "--max_old_space_size" parameter locally for the "test:unit" task, I'll send a test PR to check if this solve the issue.

```
<--- Last few GCs --->

[3543:0x56a2ae0]   120384 ms: Mark-Compact 4042.3 (4137.9) -> 4030.0 (4141.9) MB, 1999.0 / 0.0 ms  (average mu = 0.520, current mu = 0.039) allocation failure; scavenge might not succeed
[3543:0x56a2ae0]   123710 ms: Mark-Compact 4046.6 (4142.1) -> 4034.3 (4146.1) MB, 3250.0 / 0.0 ms  (average mu = 0.282, current mu = 0.023) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by Neurone** [comment]
@svienot Ok, I found the problem and I opened an issue for that #606

**Comment by Neurone** [comment]
@svienot I noticed the current published release does not contain the tag version, but only the commit hash.

This happens if the tags are not find in the repo, so I suspect this happens because the process that created the build has cloned the project without pulling the tags. I think it's the default git behaviour if you omit the --tags flag.

Immagine 2023-05-19 141917

**Pull request merged**
